######tls_private_key is used to generate RSA encrypted private and public key-pair and also encodes it as PEM. using local_file, 
######we will save the private key generated by tls_private_key on our host system to be used later as if we require to connect to our instance via SSH

# Generates RSA Keypair
resource "tls_private_key" "devopskey" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

# Save Private key locally
resource "local_file" "private_key" {
  content  = "tls_private_key.devopskey.private_key_pem"
  filename = "devops.pem"
}

# Upload public key to create keypair on AWS
resource "aws_key_pair" "devops" {
  key_name   = "webserver"
  public_key = "tls_private_key.devops.public_key_openssh"
}
